### ISSUE TITLE
不能运行 dev 

### ISSUE THREAD

**Issue by JsBlueCat** [MangoTsing/vite-electron-quick#13]
```
PS F:\stereo-camera> npm run dev

> stereo-camera@0.0.1 dev
> npm run dev:all


> stereo-camera@0.0.1 dev:all
> concurrently -n=vue,ele -c=green,blue "npm run dev:vue" "npm run dev:ele"

[vue] 
[vue] > stereo-camera@0.0.1 dev:vue
[vue] > vite
[vue]
[ele] 
[ele] > stereo-camera@0.0.1 dev:ele
[ele] > node script/build --env=development --watch
[ele]
[vue] events.js:292
[vue]       throw er; // Unhandled 'error' event
[vue]       ^
[vue]
[vue] Error: spawn F:\stereo-camera\node_modules\esbuild\esbuild.exe ENOENT
[vue]     at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
[vue]     at onErrorNT (internal/child_process.js:465:16)
[vue]     at processTicksAndRejections (internal/process/task_queues.js:80:21)
[vue] Emitted 'error' event on ChildProcess instance at:
[vue]     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
[vue]     at onErrorNT (internal/child_process.js:465:16)
[vue]     at processTicksAndRejections (internal/process/task_queues.js:80:21) {
[vue]   errno: -4058,
[vue]   code: 'ENOENT',
[vue]   syscall: 'spawn F:\\stereo-camera\\node_modules\\esbuild\\esbuild.exe',
[vue]   path: 'F:\\stereo-camera\\node_modules\\esbuild\\esbuild.exe',
[vue]   spawnargs: [ '--service=0.9.4', '--ping' ]
[vue] }
[vue] npm ERR! code 1
[vue] npm ERR! path F:\stereo-camera
[vue] npm ERR! command failed
[vue] npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c vite
[vue] 
[vue] npm ERR! A complete log of this run can be found in:
[vue] npm ERR!     C:\Users\Cery\AppData\Local\npm-cache\_logs\2021-03-19T15_33_00_423Z-debug.log
[vue] npm run dev:vue exited with code 1
[ele] Error: Timed out waiting for: http://localhost:8889/index.html
[ele]     at MergeMapSubscriber.project (F:\stereo-camera\node_modules\wait-on\lib\wait-on.js:132:31)
[ele]     at MergeMapSubscriber._tryNext (F:\stereo-camera\node_modules\rxjs\internal\operators\mergeMap.js:67:27)
[ele]     at MergeMapSubscriber._next (F:\stereo-camera\node_modules\rxjs\internal\operators\mergeMap.js:57:18)
[ele]     at MergeMapSubscriber.Subscriber.next (F:\stereo-camera\node_modules\rxjs\internal\Subscriber.js:66:18)
[ele]     at AsyncAction.dispatch (F:\stereo-camera\node_modules\rxjs\internal\observable\timer.js:31:16)
[ele]     at AsyncAction._execute (F:\stereo-camera\node_modules\rxjs\internal\scheduler\AsyncAction.js:71:18)
[ele]     at AsyncAction.execute (F:\stereo-camera\node_modules\rxjs\internal\scheduler\AsyncAction.js:59:26)
[ele]     at AsyncScheduler.flush (F:\stereo-camera\node_modules\rxjs\internal\scheduler\AsyncScheduler.js:52:32)
[ele]     at listOnTimeout (internal/timers.js:554:17)
[ele]     at processTimers (internal/timers.js:497:7)
[ele] npm ERR! code 1
[ele] npm ERR! path F:\stereo-camera
[ele] npm ERR! command failed
[ele] npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node script/build --env=development --watch
[ele] 
[ele] npm ERR! A complete log of this run can be found in:
[ele] npm ERR!     C:\Users\Cery\AppData\Local\npm-cache\_logs\2021-03-19T15_33_05_739Z-debug.log
[ele] npm run dev:ele exited with code 1
npm ERR! code 1
npm ERR! path F:\stereo-camera
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c concurrently -n=vue,ele -c=green,blue "npm run dev:vue" "npm run dev:ele"

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Cery\AppData\Local\npm-cache\_logs\2021-03-19T15_33_05_819Z-debug.log
npm ERR! code 1
npm ERR! path F:\stereo-camera
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c npm run dev:all

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Cery\AppData\Local\npm-cache\_logs\2021-03-19T15_33_05_870Z-debug.log
```
下面是log ，求助 ！

```
0 verbose cli [
0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\Users\\Cery\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'run',
0 verbose cli   'dev:vue'
0 verbose cli ]
1 info using npm@7.6.3
2 info using node@v14.16.0
3 timing config:load:defaults Completed in 2ms
4 timing config:load:file:C:\Users\Cery\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 2ms
7 timing config:load:env Completed in 1ms
8 timing config:load:file:F:\stereo-camera\.npmrc Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:F:\cadence_workspace\.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:C:\Users\Cery\AppData\Roaming\npm\etc\npmrc Completed in 1ms
13 timing config:load:global Completed in 1ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 2ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 11ms
19 verbose npm-session f9712d0d074830cd
20 timing npm:load Completed in 19ms
21 timing command:run Completed in 297ms
22 verbose stack Error: command failed
22 verbose stack     at ChildProcess.<anonymous> (C:\Users\Cery\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
22 verbose stack     at ChildProcess.emit (events.js:315:20)
22 verbose stack     at maybeClose (internal/child_process.js:1048:16)
22 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
23 verbose pkgid stereo-camera@0.0.1
24 verbose cwd F:\stereo-camera
25 verbose Windows_NT 10.0.19041
26 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Cery\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev:vue"
27 verbose node v14.16.0
28 verbose npm  v7.6.3
29 error code 1
30 error path F:\stereo-camera
31 error command failed
32 error command C:\WINDOWS\system32\cmd.exe /d /s /c vite
33 verbose exit 1

```

**Comment by z-950** [comment]
你是不是用了淘宝镜像。
`npm cache clean -f`然后不要用淘宝镜像再试一下。

**Comment by z-950** [comment]
还不行再清掉esbuild的二进制缓存
