### ISSUE TITLE
找不到dist/main/build.js文件

### ISSUE THREAD

**Issue by Kimentanm** [MangoTsing/vite-electron-quick#14]
![image](https://user-images.githubusercontent.com/25970284/113106796-c0c52680-9235-11eb-9b38-fd4ca58f0297.png)

**Comment by Kimentanm** [comment]
npm run dev 日志

```shell
[ele] TypeError: esbuild.startService is not a function
[ele]     at Object.buildStart (/Users/kimen/WebStormProjects/vite-electron-quick/node_modules/rollup-plugin-esbuild/dist/index.js:81:33)
[ele]     at /Users/kimen/WebStormProjects/vite-electron-quick/node_modules/rollup/dist/shared/rollup.js:18863:25
[ele]     at processTicksAndRejections (internal/process/task_queues.js:94:5)
[ele]     at async Promise.all (index 2)
[ele]     at async Object.rollupInternal (/Users/kimen/WebStormProjects/vite-electron-quick/node_modules/rollup/dist/shared/rollup.js:20206:9)
[ele]     at async Task.run (/Users/kimen/WebStormProjects/vite-electron-quick/node_modules/rollup/dist/shared/watch.js:751:22)
[ele]     at async Watcher.run (/Users/kimen/WebStormProjects/vite-electron-quick/node_modules/rollup/dist/shared/watch.js:683:13) {
[ele]   code: 'PLUGIN_ERROR',
[ele]   plugin: 'esbuild',
[ele]   hook: 'buildStart'
[ele] }
[ele] [2021-03-31T07:33:32.864Z] [electron-connect] [server] started electron process: 64669
[ele] [2021-03-31T07:33:32.865Z] [electron-connect] [server] server created and listening on 30080
```

**Comment by Kimentanm** [comment]
将rollup-plugin-esbuild的版本升级后，问题解决了
![image](https://user-images.githubusercontent.com/25970284/113108172-45fd0b00-9237-11eb-9215-4440cdf59c9a.png)

**Comment by MangoTsing** [comment]
在 vite 2.1.0 版本时，有一个修改，修改了 bundle vite.config.ts 部分，我这边也更新一下，可以看具体提交 https://github.com/vitejs/vite/pull/2517
